# Generated by Django 4.1.3 on 2022-11-04 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cumulus", "0003_dailydata_avg_wind_direction_data_daily_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailydata",
            options={"ordering": ("-date",)},
        ),
        migrations.AlterField(
            model_name="data",
            name="daily_data",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="data",
                to="cumulus.dailydata",
            ),
        ),
    ]
